language: node_js
node_js:
  - "14"
dist: bionic
services:
    - mongodb
env:
    - DB_PATH=mongodb://127.0.0.1:27017/im-api-test JWT_SECRET=ci-env-secret EMAIL_SENDER_ADDRESS=admin@example.com FRONTEND_URL=http://127.0.0.1:3000
cache: 
    directories:
        - node_modules
install:
    - npm install
script: 
    - sleep 15
    - npm run test-ci