version: '3.1'
services:
    web:
        build: .
        command: npm run dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        env_file:
            - config/dev.env
    web_test:
        build: .
        command: npm test
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - config/test.env
    db:
        image: mongo:4.2.7
        ports:
            - 27017:27017